apiVersion: apps/v1
kind: Deployment
metadata:
  name: logit-model-deployment
spec:
  replicas: 3 
  selector:
    matchLabels: 
      app: logit-model
  template:
    metadata:
      labels:
        app: logit-model 
    spec:
      containers:
      - name: logit-model 
        image: dandandeo/logit_app:latest 
        ports:
        - containerPort: 8501